# -*- coding: utf-8 -*-
"""конкуренты 2.0

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1H0uL3c1ppOBjCWhGWLAYjYXUsz_STFVX
"""

# спарсим первый сайт, посмотрим на цены и виды тренировок
import requests
from bs4 import BeautifulSoup
import pandas as pd
import re

url = "https://wsstudio.info/tseny/"
response = requests.get(url)
html_content = response.text

soup = BeautifulSoup(html_content, 'html.parser')

price_items = soup.find_all('span', class_='elementor-price-list-price')
services_items = soup.find_all('span', class_='elementor-price-list-title')

services = []
prices = []

fetched_items = list(zip( services_items, price_items))

for fetched_service, fetched_price in fetched_items:
    services.append(fetched_service.text.strip())
    prices.append(fetched_price.text)

df2 = pd.DataFrame({
    'Название услуги': services,
    'Цена': prices
})

print(df2)

with pd.ExcelWriter('services_data1.xlsx') as writer:
    df2.to_excel(writer, sheet_name='Services', index=False)

# второй сайт по такой же логике
import requests
from bs4 import BeautifulSoup
import pandas as pd
import re

url = "https://moyfit.com/?ysclid=m8c5kffnqy385506837#rec778251736"
response = requests.get(url)
html_content = response.text

soup = BeautifulSoup(html_content, 'html.parser')

price_items = soup.find_all('div', class_='t1072__price t-title t-title_xs')
services_items = soup.find_all('div', class_='t-card__title t-name t-name_md')
membership_items = soup.find_all('div', class_='t-card__title t-name t-name_lg')
services = []
prices = []
memberships = []

fetched_items = list(zip( membership_items, price_items))

for fetched_membership, fetched_price in fetched_items:
    memberships.append(fetched_membership.text.strip())
    prices.append(fetched_price.text)

for service in services_items:
    services.append(service.text.strip())

df = pd.DataFrame({
    'Вид абонемента': memberships,
    'Цена': prices
})
df1 = pd.DataFrame({
    'Название услуги': services,
})
print(df)
print(df1)

with pd.ExcelWriter('services_data2.xlsx') as writer:
    df.to_excel(writer, sheet_name='Memberships', index=False)
    df1.to_excel(writer, sheet_name='Services', index=False)

import requests
from bs4 import BeautifulSoup
import pandas as pd

url = "https://reshape.global/price#accord10"
response = requests.get(url)
html_content = response.text

soup = BeautifulSoup(html_content, 'html.parser')
buttons = soup.find_all('a', class_='tn-atom')

result = []

used_buttons = set()

for button in buttons:
    if button.text == '+':
        continue
    button_text = button.text.strip()
    related_texts = []
    prices = []
    name = None
    processed_ids = set()

    for elem in button.find_all_previous(class_='tn-atom'):
        parent = elem.find_parent('div', class_='tn-elem')


        if parent and parent.has_attr('data-elem-id'):
            if parent['class'][-1] in used_buttons:
                continue
            used_buttons.add(parent['class'][-1])
            elem_id = parent['data-elem-id']

            if parent.get('data-elem-type') == 'text':
                text = elem.text.strip()
                if 'Бесконечно много часов тренировок в любое время суток' in text:
                    continue
                if 'Тренировки на РЕФОРМЕРАХ проходят на Парке Культуры' in text:
                    continue
                if 'Индивидуальные тренировкиЛЮБОЕ ВРЕМЯ' in text:
                    continue
                if '₽' in text and not '*' in text:
                    prices.append(text)
                    continue
                if text == text.upper():
                    name = text
                    continue

                if '+' in text or '%' in text or '*' in text or 'без заморозки' in text or 'Для тренировок до 16:00и по выходным' in text:
                    continue
                if text:
                    related_texts.append(text)

    # Восстанавливаем оригинальный порядок
    related_texts.reverse()
    prices.reverse()

    result.append({
        'name': name,
        'prices': prices,
        'related_texts': related_texts
    })
data = {}

for item in result:
    data[item['name']] = (item['related_texts'], item['prices'])

# Вывод результатов
for name, prices in data.items():
    print(f"Имя: {name}")
    print("Связанные тексты:")
    for i, text in enumerate(prices[0], 1):
        print(f"{i}. {text}")
    print("Цены:")
    for i, text in enumerate(prices[1], 1):
        print(f"{i}. {text}")
    print("\n" + "="*50 + "\n")